In [1]:
#!/usr/bin/env python
# coding: utf-8

# In[34]:


import pandas as pd
import numpy as np
df=np.random.randint(30,100,(10,3))#creating random dataset
df=pd.DataFrame(df,columns=['no_of_vehicle','avg_speed','avg_distance_btw_them'])
df.to_csv('data.csv')
df=df.values
prob_dim=(len(df))
pop_size=30
data_set=[[0 for x in range(prob_dim)] for x in range(pop_size)]

def generate(df):
    no_of_lane=prob_dim
    for i in range(pop_size):
        for j in range(no_of_lane):
            data_set[i][j]=((df[j][0]*df[j][1])//df[j][2])*np.random.randint(1,7)#(between 0-8*(timeconstant_for_lane))
            # print(data_set[i][j])
    return data_set


pop=generate(df)


# In[35]:


"""f(x)=x1^2+x2^2+x3^2
0=<x<=8
size=6"""

pop=np.array(data_set)
"""initialization for random samples
  x=xmin+rand(0,1)*(xmax-xmin)"""
for i in pop:
    print(i)


# In[36]:


def objective(pop):
    f=[]
    for i in range(pop.shape[0]):
        f.append(pop[i,0]**2+pop[i,1]**2+pop[i,2]**2)
    return f
def fitness(pop):
    fit=[]
    f=objective(pop)
    for i in f:
        if(i<0):
            fit.append(1-i)
        else:
            fit.append(1/(1+i))
    return fit
trial=[0]*pop.shape[0]
best=pop[np.argmax(fitness(pop)),:]
print("Population is ",pop)
print("Fitness of population ",fitness(pop))
print("Trial value of population ",trial)
print("best soluntion is ",best)


# In[37]:


#Employee Bee phase
import random
lb=0
up=8
def employee(pop,lb,ub,fit,trial):
    for i1 in range(pop.shape[0]):
        j=random.randint(0,2)
        p=random.randint(0,2)
        while(i1==p):
            p=random.randint(0,2)
        new=pop[i1,j]+np.random.uniform(low=-1,high=1,size=(1,))*(pop[i1,j]-pop[p,j])
        if(new>ub):
            new=ub
        if(new<lb):
            new=lb
        new_pop=np.array([pop[i1,:].copy()])
        new_pop[0,j]=new
        #print(new_pop.shape)
        f=fitness(new_pop)
        if(f>fit[i1]):
            pop[i1,:]=new_pop
            trial[i1]=0
        else:
            trial[i1]=trial[i1]+1
    return pop

print(employee(pop,lb,up,fitness(pop),trial))
print(trial)


# In[ ]:





# In[ ]:





# In[ ]:


[ 64 534 528 224 288 390 344 103 256  34]
[320  89 528  56 216  78 344 412 192 204]
[320 356 176 224 288 468 258 309  64  68]
[ 64 445 176 336 216 390  86 103 320 204]
[128 178 352 336 432 312  86 618 192  34]
[192 534 176 224 288 390 258 515 384 170]
[256 534 176  56 216  78 258 515 384 102]
[192 445  88 336 144 468 258 103 384 102]
[256 267  88 112 216 312 430 309 384 170]
[256 445 264 280 144 234 172 309 192 204]
[320 445 352 168  72 312 344 103 384 102]
[320  89 528  56 360 156 516 515  64  34]
[192 445  88 168 216  78 258 103 192 102]
[256 445 440 280  72 156 516 103 256 204]
[128 445  88  56 360 156  86 103 256  68]
[128 267 352 336  72 468 516 309 320  34]
[256 267 440 336 216 390 344 515 256 102]
[256  89 528  56  72 468 516 206  64  34]
[128  89 176 336 288 312 258 515 384  68]
[128  89 440 112 360 234 344 412 128 136]
[192 445 440 112 288 234 344 618 192 204]
[ 64 445 264  56 288 390 516 103 256 102]
[320  89 176 112 216  78 172 206 320 102]
[ 64 534 352 224  72 156 172 618 3